### ISSUE TITLE
Link github and sphinx documentation

### ISSUE THREAD

**Issue by mchandra** [shankar1729/qimpy#1]
It would be nice if pages inside each source folder in github show/link to the sphinx documentation.

**Comment by shankar1729** [comment]
Added links to sphinx documentation in each sub-package. Took the most straightforward approach here of manually adding a markdown link to the readthedocs page. We can later edit these READMEs to reproduce the first sentence or paragraph of the API documentation if needed, but would then need to worry about keeping those in sync.
